---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    JOBS: 1
    secure: fOTO/HpUT0xsfml9iXuEL9qBu0NVErcig6CmrS1DFv7f4x9/mYQMNzLUv5b6VBPqGHeFNHiGaUUza3Ufc5KpL7DOu/1y6TFQlSoM6MRRdIXb+50MObvkJ4wXwYJH7Zrb4g8RTaBOY9uU5XQkm/E6GWWF3NiYFoVzCYPNSgAALko1caoEX2hoJNXJSd0T4G+gxtxc2g08RGunBPLqIyy2avMRN4yq0WDN2NbBrztM01FA5RoOLPyX0hhzyIZ+45z34wKvZtu7rj9h1KbFOZOVFJWpHDa0bXxhF63ldxPINe2QMOSsOD22Czk1+IKyC+88gtkvUq7pGUaJK6YdVDRcW9G/DMHVy/IE2aFabrPDVgzrmeCoVKzATzt8nMfIMTTu9Unoa5fdohpJ0NPhYnPfVAGfJ+2MPITgP+x2X6M5+KgHCBdaIgwBVnZE9DTb1L9c/Eh50zeHHbfv9L+NVlbQFzMWNj+kKWMj0qwh6JPpSFiKaOvTK6XP+NSUc7euAZgqK6lwqS07pvcql4qvzbeRWyn/GZuRHOGvfkUNuvLee8dMKfpF3s1VQ6blHHqKB8qH2ifxawiztWgUkYxK0GFTk//ZopLzP90bLl0JiGlg517tp5V9eBOK5ZlPwsSOhD+wta9gCssPjK4i2H2IwLox7AqXegigBMdqIbXz9LaFVAY=

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/
    # greenkeeper branches
    - /^greenkeeper\/.*$/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - COVERAGE=true yarn test
        - codecov

    # - name: "Floating Dependencies"
    #   script:
    #     - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    rooms:
      secure: tOeQS4/RpG2hu+5L0qDs0m5s200m23wPAP2KUrsFDCTugARyNqcMHHLirKmRdrJi4G0pQTL9U9L1+uEUIgL4x2NRKcvlt5vDlITUvWo1xGjKSz+2acLNXtV4dRK73yUW6witx0VRspRvwEG/Y7LewHJDdPpo2KpXTfQ3VO6y7O3vqsAVcLvO6vim6qK+Yq8RWed0XKy+9T4sckRmAcWV0lLJEzFV8kfcvvDbSFcRAcJqE0oBWIRqKVozi18Z1L2aWxKl8LpJyU7YgLW0q1NxxfDPfpY9sqIgmkHosuUt9Q+Xj042Hp8FoZbHDeCkAWZ/g+BbPtXUVOeIA5udM5MDcIHSt2D7y/6wR6WuqoqVkJZz3UsxmP2hrU5RJNWVgJ+/AGkYaSKCm6gpsVrqQRt8829MxvVpmFh8t5gNODMfCcf2gBjHqT0Y59s5WmPHmQeMuMXNlUNwEM/lodE1v4FMoOxHPGUnqTGoMK98PQO6uunH8RIC8Eg1yBPoRzlZcJfM4e1ZGaHGhlpZKKAPRf/w2OmQCZfzIYw2bbf6Eq9VFBeKjDplwaY5jyrgi6HD3AU7Tj72XdHbV+ugHUdlXldmdCJ0Fbg5UYDNDg92VrDUeZGotpGr0j52m2rKnicELnAZb8/Z/sRhwTTedwd9MvHezbir3YXlxSPcEv8Lw37Og3I=

deploy:
  provider: npm
  skip_cleanup: true
  email: devo.tox.89@gmail.com
  api_key:
      secure: EfQbiaUMapxYcocCH35YQek33IqYXSnSLu6/jZFIPGMjKMxb6zQHoVvTcS8MD6rf3Hrtt6R08lZfEO9I909VKxgx11sMbPkApAOpT+pyoJXGfqMvQ3nzuHOOEgLJh/Y9DOj5emirDdnoxVotn1jeuoIcuJ8SUvI6E6qKpLXRylwDhhriExeK8NuTb9mnjPCZGjaEdn2MzK4wAGvMWodIGPEh8EpxHKFVKLGzH3PKcma+fzqFX9Mc5piY8zIpRXrsyp7Gakx09yl1N71uDVEIP8gYNNY98/GtxU7mxkjD56M2swZPjEyG52uolzd7c7Mmj67GNogsWW6WFThLmlawjisaYPFV9NaK5Je5i6VnNRTa68U46UZbB5hS0ovOmrhK6+ZSdUr8wQW+KnTWZ8zv04va9zDjEMebn5DMHBz6Yx/CvETXPKjebKdaAyb1YugOKvsDIvUs/BJl53IyqPcF3yeTSxhW5pFOBAoTrnG17cGyet2g04+GBBWliOXnWW5TLOhATSk83oicOGFgegXmI6QEipC3g8N67GTb5CC11zLJeYbWP8Sj5RNP+vnxn4WhU275qzPgPiM5qp771N6Ls+X6VtiEkQmQGHf1Iux4Xl6NAeJ+3/7+QFeqghYOga1LIcDPrmznpXD1EEPLl6DXvgcoCY1niRaGqsW55lUD5Uk=
    on:
    tags: true
    repo: devotox/ember-paper-input-mask
